- name: Remove secret
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Remove secret
    hasnimehdi91.keepass.secret_remover:
      db_path: "secrets.kdbx"
      db_password: "password"
      secret_path: "foo/bar/secret"
    register: removed_secret
  - debug:
      msg: "{{ removed_secret.removed }}"

  - name: Remove group and all its content
    hasnimehdi91.keepass.secret_remover:
      db_path: "secrets.kdbx"
      db_password: "password"
      secret_path: "foo"
      target: group
      recurse: true
    register: removed_group
  - debug:
      msg: "{{ removed_group.removed }}"
