- name: Write secret
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Write secret
    hasnimehdi91.keepass.secret_writer:
      db_path: "secrets.kdbx"
      db_password: "password"
      secret_path: "foo/bar/secret"
      secret_value:
        username: "John"
        password: "Doe"
        custom_properties:
          gender: "Male"
      force: false
    register: written_secret
  - debug:
      msg: "{{ written_secret.changed }}"
