- name: Read secret
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Read secret
    hasnimehdi91.keepass.secret_reader:
      db_path: "secrets.kdbx"
      db_password: "password"
      secret_path: "foo/bar/secret"
    register: read_secret
  - debug:
      msg: "{{ read_secret.secret }}"
